export enum MASTER_MAINTENANCE_PAGE {
  // #region Dashboard
  BTN_CREATE_STORE = '//*[text()=" 新規作成"]',
  BTN_SEARCH = '//*[@title="検索"]',
  TXT_COMPANY = '(//*[@placeholder="選択してください"])[1]',
  TXT_AREA = '(//*[@placeholder="選択してください"])[2]',
  TXT_STORE = '//*[@placeholder="員名または社員コード"]',
  BTN_EXCEL_EXPORT = '//*[text()=" Excel出力"]',
  GRID_DATE = '//tbody//tr',

  // #region Store
  TAB_STORE = '//button[text()="店舗"]',
  TXT_COMPANY_NAME = '//*[@name="company_name"]',
  TXT_COMPANY_NAME_FURIGANA = '//*[@name="company_name_furigana"]',
  TXT_COMPANY_CODE = '(//input[@placeholder="選択してください"])[3]',

  // #region Create Store Modal
  TXT_STORE_CODE = '//*[@name="code"]',
  TXT_ZONE = '(//*[@placeholder="選択してください"])[4]',
  TXT_STORE_NAME = '(//*[@placeholder="入力してください"])[2]',
  TXT_HEALTH_CENTER = '//*[@name="health_center"]',
  TXT_EMPLOYEE_CAPACITY = '//*[@name="employee_capacity"]',
  TXT_PHARMACY_STAFF = '//*[@name="pharmacy_staff"]',
  TXT_GENERAL_STAFF = '//*[@name="general_staff"]',
  TXT_SUPERVISOR = '(//*[@placeholder="社員名または社員コード"])[1]',
  TXT_MANAGER = '(//*[@placeholder="社員名または社員コード"])[2]',
  BTN_RETURN = '//*[contains(text()," 戻る")]',
  BTN_SUBMIT = '//*[text()="登録する"]',

  // #region Employee
  TAB_EMPLOYEE = '//button[text()="社員"]',
  TXT_EMPLOYEE_NAME = '//*[@placeholder="社員名または社員コード"]',
  BTN_CREATE_EMPLOYEE = '//*[text()=" 社員新規作成"]',
  TXT_EMPLOYEE_CODE = '//*[@name="code"]',
  TXT_LAST_NAME = '//*[@name="last_name"]',
  TXT_FIRST_NAME = '//*[@name="first_name"]',
  TXT_LAST_NAME_FURIGANA = '//*[@name="last_name_kana"]',
  TXT_FIRST_NAME_FURIGANA = '//*[@name="first_name_kana"]',
  TXT_AFFILIATED_COMPANY = '(//*[@placeholder="入力してください"])[2]',
  TXT_AFFILIATED_STORE = '(//*[@placeholder="入力してください"])[3]',
  TXT_GENDER = '//*[@name="gender"]',
  DATETIME_BIRTHDAY = '//*[text()="生年月日"]/..//*[contains(@class,"lucide-calendar")]',
  TXT_EMPLOYEE_TYPE = '//*[@name="employmentType"]',
  TXT_ROLE = '//*[@name="role"]',
  TXT_GROUP_LEADER = '(//*[@placeholder="社員名または社員コード"])[2]',
  TXT_TIME_APPROVER = '(//*[@placeholder="社員名または社員コード"])[3]',
  TXT_COURSE_CATEGORY = '//*[@name="course_type"]',
  DATETIME_JOIN_DATE = '//*[text()="入社日"]/..//*[contains(@class,"lucide-calendar")]',
  BTN_SAVE = '//*[text()="登録"]',

  // #region Company
  TAB_COMPANY = '//button[text()="会社"]',
  TXT_COMPANY_FILTER = '//*[@placeholder="会社名または会社コード"]',
  BTN_CREATE_COMPANY = '//*[text()=" 会社新規作成"]',
  TXT_SORT = '//*[text()="並び順:"]/following-sibling::select',
  TXT_COMPANY_CODE_CREATE = '(//*[@placeholder="入力してください"])[1]',
  TXT_COMPANY_NAME_CREATE = '(//*[@placeholder="入力してください"])[2]',
  TXT_COMPANY_DIRECTOR = '(//*[@placeholder="入力してください"])[3]',
  TXT_COMPANY_NAME_FURIGANA_CREATE = '//*[@name="name_kana"]',
  TXT_COMPANY_DIRECTOR_FURIGANA = '//*[@name="representative_kana"]',
  TXT_ADDRESS = '//*[@name="postal_code"]',
  BTN_LOOKUP = '//*[text()="住所入力"]',
  TXT_DISTINGUISH = '//*[@name="category"]',
  TXT_CLOSING_DAYS = '//*[@name="closing_day"]',
  BTN_ADD = '//*[text()=" 追加"]',
  TXT_DEPARTMENT_NAME = '//*[@placeholder="部門名"]',
  TXT_DEPARTMENT_INTRODUCTION = '//*[@placeholder="部門紹介"]',
  TXT_UPLOAD = '//*[@id="file-upload"]',

  // #region Area
  TAB_AREA = '//button[text()="エリア・ゾーン"]',
  BTN_AREA = '//button[text()="エリア"]',
  BTN_ZONE = '//button[text()="ゾーン"]',
  BTN_ADD_ZONE = '//*[text()=" 新規作成"]',
  TXT_ZONE_CODE = '//*[@name="code"]',
  TXT_ZONE_NAME = '//*[@name="name"]',
  TXT_CONTRACT_DISPLAY_NAME = '//*[@name="contract_name"]',
  TXT_RANK = '//*[@name="rank"]',
  CHECK_HIDDEN = '//*[@name="hidden"]',

  // #region Authority
  TAB_AUTHORITY = '//button[text()="権限"]',
  TXT_AUDIENCE = '//*[@placeholder="社員名または社員コード"]',
  BTN_ADD_PERMISSION = '//*[text()=" 新規作成"]',
  TXT_GROUP_NAME = '//*[@id="groupName"]',
  TXT_EMPLOYEE_LOOKUP = '//*[@placeholder="社員名か社員コードを入力"]',
  BTN_RIGHT = '//*[contains(@class,"lucide-chevrons-right")]',
  BTN_LEFT = '//*[contains(@class,"lucide-chevrons-left")]',
  BTN_PROCESS = '//*[text()=" 権限設定に進む"]',
}

export enum LEDGER_DETAIL_PAGE {
  // #region Basic Ledger
  TAB_BASIC_LEDGER = '//button[text()="基本台帳"]',
  BTN_UPDATE = '//*[text()="更新する"]',
  TXT_LAST_NAME = '//*[@name="last_name"]',
  TXT_FIRST_NAME = '//*[@name="first_name"]',
  TXT_LAST_NAME_KANA = '//*[@name="last_name_kana"]',
  TXT_FIRST_NAME_KANA = '//*[@name="first_name_kana"]',
  TXT_OLD_LAST_NAME = '//*[@name="old_last_name"]',
  TXT_OLD_FIRST_NAME = '//*[@name="old_first_name"]',
  TXT_OLD_LAST_NAME_KANA = '//*[@name="old_last_name_kana"]',
  TXT_OLD_FIRST_NAME_KANA = '//*[@name="old_first_name_kana"]',
  RADIO_GENDER = '//*[@for="gender"]/following-sibling::*//*[@type="radio"]',
  TXT_BIRTHDAY = '//*[@for="birth_date"]/following-sibling::*//input',
  BTN_APPLY = '//button[text()="適用"]',
  TXT_EMAIL = '//*[@name="email"]',
  TXT_PHONE = '//*[@name="phone"]',
  TXT_NEAREST_STATION = '//*[@for="location_station_id"]/following-sibling::*//input',
  OPT_NEAREST_STATION = '//*[@for="location_station_id"]/following-sibling::*//*[@class="font-medium"]',
  TXT_DIRECTION_TO_STATION = '//*[@name="route_to_station"]',
  RADIO_COMPUTE_BY_TRAIN = '//*[@for="commute_by_train"]/following-sibling::*//*[@type="radio"]',
  RAIDO_COMPUTE_BY_CAR = '//*[@for="commute_by_car"]/following-sibling::*//*[@type="radio"]',
  TXT_NUM_OF_CAR = '//*[@name="cars_owned"]',
  TXT_ZIP_CODE = '//*[@name="current_address.postal_code"]',
  TXT_HOUSE_NUMBER = '//*[@name="current_address.street_address"]',
  TXT_BUILDING_NAME = '//*[@name="current_address.building_name"]',
  TXT_PHONETIC = '//*[@name="current_address.furigana"]',
  RADIO_PHARMA_LICENSE = '//*[@for="has_pharmacist_license"]/following-sibling::*//*[@type="radio"]',
  RADIO_SELLER = '//*[@for="is_registered_seller"]/following-sibling::*//*[@type="radio"]',
  RADIO_MARRIED = '//*[@for="has_spouse_info"]/following-sibling::*//*[@type="radio"]',
  TXT_EDUCATION_LEVEL = '//*[@name="highest_education_level"]',
  CHK_IS_GRADUATED = '//*[@name="is_graduate_school"]',
  SELECT_EMERGENCY_RELATIONSHIP = '//*[@name="emergency_contact_relationship"]',
  SELECT_TAX_FORM = '//*[@name="tax_table"]',
  SELECT_DISABILITY = '//*[@name="disability_classification"]',
  SELECT_WIDOW = '//*[@name="is_widow"]',
  TXT_EMERGENCY_PHONE = '//*[@name="emergency_contact_number"]',
  TXT_PROFILE_PICTURE = '//*[@name="profile_photo"]',
  TXT_INTRODUCE_VIDEO = '//*[@name="introduction_video"]',
  TXT_RESIDENT_ZIP_CODE = '//*[@name="resident_address.postal_code"]',
  TXT_RESIDENT_HOUSE_NUMBER = '//*[@name="resident_address.street_address"]',
  TXT_RESIDENT_BUILDING_NAME = '//*[@name="resident_address.building_name"]',
  TXT_RESIDENT_PHONETIC = '//*[@name="resident_address.furigana"]',
  TXT_BANK_CODE = '//*[@name="bank_code"]',
  TXT_BANK_NAME = '//*[@name="bank_name"]',
  TXT_BANKER_KANA = '//*[@name="bank_name_kana"]',
  TXT_BRANCH_CODE = '//*[@name="branch_code"]',
  TXT_BRANCH_NAME = '//*[@name="branch_name"]',
  TXT_BRANCH_KANA = '//*[@name="branch_name_kana"]',
  TXT_ACCOUNT_HOLDER = '//*[@name="account_holder_name"]',
  TXT_ACCOUNT_HOLDER_KANA = '//*[@name="account_holder_name_kana"]',
  SELECT_ACCOUNT_TYPE = '//*[@name="account_type"]',
  TXT_ACCOUNT_NUMBER = '//*[@name="account_number"]',
  TXT_RETIRE_CODE = '//*[@name="post_retirement_address.postal_code"]',
  TXT_RETIRE_ADDRESS = '//*[@name="post_retirement_address.street_address"]',
  TXT_RETIRE_BUILDING_NAME = '//*[@name="post_retirement_address.building_name"]',
  TXT_RETIRE_PHONETIC = '//*[@name="post_retirement_address.furigana"]',
  BTN_CURRENT_ADDRESS_LOOKUP = '//*[@name="current_address.postal_code"]/following-sibling::button',
  BTN_RESIDENT_ADDRESS_LOOKUP = '//*[@name="resident_address.postal_code"]/following-sibling::button',
  BTN_RETIRE_ADDRESS_LOOKUP = '//*[@name="post_retirement_address.postal_code"]/following-sibling::button',
  LBL_LOOKUP_SUCCESS = '//*[text()="The address has been auto-populated. Enter your street address."]',
}
